/**
 * @fileoverview ArcGIS Maps SDK for JavaScript 4.33 API Documentation
 * Complete API reference for js_interop implementation
 * @version 4.33
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/}
 */

/**
 * @namespace esri
 * @description The esri namespace is the root of the ArcGIS Maps SDK for JavaScript API
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/}
 */

// =============================================================================
// CORE CLASSES
// =============================================================================

/**
 * @class esri.core.Accessor
 * @description The base class of most ArcGIS Maps SDK for JavaScript objects
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-core-Accessor.html}
 */

/**
 * @class esri.core.Collection
 * @description A generic collection class used throughout the ArcGIS Maps SDK
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-core-Collection.html}
 */

/**
 * @class esri.core.Error
 * @description The Error class represents an error that may be generated by the API
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-core-Error.html}
 */

/**
 * @class esri.core.Handles
 * @description Utility for managing a collection of handles for Accessor.watch()
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-core-Handles.html}
 */

/**
 * @class esri.config
 * @description Global configuration object for the ArcGIS Maps SDK
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-config.html}
 */

// =============================================================================
// MAP AND SCENE CLASSES
// =============================================================================

/**
 * @class esri.Map
 * @description The Map class contains properties and methods for storing, managing, and overlaying layers
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-Map.html}
 */

/**
 * @class esri.WebMap
 * @description The WebMap class is a way to work with and display ArcGIS web maps
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-WebMap.html}
 */

/**
 * @class esri.WebScene
 * @description The WebScene class is a way to work with and display ArcGIS web scenes
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-WebScene.html}
 */

// =============================================================================
// VIEW CLASSES
// =============================================================================

/**
 * @class esri.views.View
 * @description The base View class for MapView and SceneView
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-views-View.html}
 */

/**
 * @class esri.views.MapView
 * @description A MapView displays a 2D view of a Map instance
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html}
 */

/**
 * @class esri.views.SceneView
 * @description A SceneView displays a 3D view of a Map or WebScene
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-views-SceneView.html}
 */

// =============================================================================
// GEOMETRY CLASSES
// =============================================================================

/**
 * @class esri.geometry.Geometry
 * @description The base class for geometry objects
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-Geometry.html}
 */

/**
 * @class esri.geometry.Point
 * @description A location defined by X, Y, and optionally Z coordinates
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-Point.html}
 */

/**
 * @class esri.geometry.Polyline
 * @description An array of paths where each path is an array of points
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-Polyline.html}
 */

/**
 * @class esri.geometry.Polygon
 * @description An array of rings where each ring is an array of points
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-Polygon.html}
 */

/**
 * @class esri.geometry.Extent
 * @description The minimum and maximum X and Y coordinates of a bounding box
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-Extent.html}
 */

/**
 * @class esri.geometry.Multipoint
 * @description An array of points
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-Multipoint.html}
 */

/**
 * @class esri.geometry.Circle
 * @description A circle geometry defined by a center point and radius
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-Circle.html}
 */

/**
 * @class esri.geometry.Mesh
 * @description A mesh represents a 3D geometry composed of triangular faces
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-Mesh.html}
 */

/**
 * @class esri.geometry.SpatialReference
 * @description Defines the spatial reference of a geometry
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-SpatialReference.html}
 */

/**
 * @class esri.geometry.geometryEngine
 * @description Client-side geometry utilities and functions
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-geometryEngine.html}
 */

// =============================================================================
// LAYER CLASSES
// =============================================================================

/**
 * @class esri.layers.Layer
 * @description The base class for all layers that can be added to a Map
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-Layer.html}
 */

/**
 * @class esri.layers.GraphicsLayer
 * @description A layer that contains one or more graphics
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GraphicsLayer.html}
 */

/**
 * @class esri.layers.FeatureLayer
 * @description A layer based on a feature service
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html}
 */

/**
 * @class esri.layers.SceneLayer
 * @description A layer for displaying large amounts of 3D data
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-SceneLayer.html}
 */

/**
 * @class esri.layers.TileLayer
 * @description A layer that displays cached tiles from a map or image service
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-TileLayer.html}
 */

/**
 * @class esri.layers.MapImageLayer
 * @description A layer that displays data from sublayers defined in a map service
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-MapImageLayer.html}
 */

/**
 * @class esri.layers.VectorTileLayer
 * @description A layer that displays cached tiles from a vector tile service
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-VectorTileLayer.html}
 */

/**
 * @class esri.layers.ImageryLayer
 * @description A layer that displays data from an imagery service
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-ImageryLayer.html}
 */

/**
 * @class esri.layers.ElevationLayer
 * @description A layer that displays elevation data
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-ElevationLayer.html}
 */

/**
 * @class esri.layers.PointCloudLayer
 * @description A layer that displays large amounts of point-based 3D geographic data
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-PointCloudLayer.html}
 */

/**
 * @class esri.layers.IntegratedMeshLayer
 * @description A layer that displays integrated mesh data
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-IntegratedMeshLayer.html}
 */

/**
 * @class esri.layers.BuildingSceneLayer
 * @description A layer that displays building scene data
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-BuildingSceneLayer.html}
 */

/**
 * @class esri.layers.GroupLayer
 * @description A container for a collection of layers
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GroupLayer.html}
 */

/**
 * @class esri.layers.GeoJSONLayer
 * @description A layer that can display GeoJSON data
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GeoJSONLayer.html}
 */

/**
 * @class esri.layers.CSVLayer
 * @description A layer that can display CSV data with location information
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-CSVLayer.html}
 */

/**
 * @class esri.layers.StreamLayer
 * @description A layer that displays real-time data
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-StreamLayer.html}
 */

/**
 * @class esri.layers.WMSLayer
 * @description A layer that displays data from a WMS service
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-WMSLayer.html}
 */

/**
 * @class esri.layers.WFSLayer
 * @description A layer that displays data from a WFS service
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-WFSLayer.html}
 */

/**
 * @class esri.layers.KMLLayer
 * @description A layer that displays data from a KML file
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-KMLLayer.html}
 */

// =============================================================================
// GRAPHICS AND SYMBOLS
// =============================================================================

/**
 * @class esri.Graphic
 * @description A graphic is composed of a geometry, symbol, attributes, and popup template
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-Graphic.html}
 */

/**
 * @class esri.symbols.Symbol
 * @description The base class for all symbols
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-Symbol.html}
 */

/**
 * @class esri.symbols.SimpleMarkerSymbol
 * @description A symbol used to visualize points
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-SimpleMarkerSymbol.html}
 */

/**
 * @class esri.symbols.SimpleLineSymbol
 * @description A symbol used to visualize polylines
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-SimpleLineSymbol.html}
 */

/**
 * @class esri.symbols.SimpleFillSymbol
 * @description A symbol used to visualize polygons
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-SimpleFillSymbol.html}
 */

/**
 * @class esri.symbols.PictureMarkerSymbol
 * @description A symbol used to visualize points using images
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-PictureMarkerSymbol.html}
 */

/**
 * @class esri.symbols.TextSymbol
 * @description A symbol used to visualize points using text
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-TextSymbol.html}
 */

/**
 * @class esri.symbols.PointSymbol3D
 * @description A symbol used to visualize points in 3D
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-PointSymbol3D.html}
 */

/**
 * @class esri.symbols.LineSymbol3D
 * @description A symbol used to visualize polylines in 3D
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-LineSymbol3D.html}
 */

/**
 * @class esri.symbols.PolygonSymbol3D
 * @description A symbol used to visualize polygons in 3D
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-PolygonSymbol3D.html}
 */

/**
 * @class esri.symbols.MeshSymbol3D
 * @description A symbol used to visualize mesh geometries in 3D
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-MeshSymbol3D.html}
 */

// =============================================================================
// RENDERERS
// =============================================================================

/**
 * @class esri.renderers.Renderer
 * @description The base class for all renderers
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-renderers-Renderer.html}
 */

/**
 * @class esri.renderers.SimpleRenderer
 * @description A renderer that uses the same symbol for all features
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-renderers-SimpleRenderer.html}
 */

/**
 * @class esri.renderers.ClassBreaksRenderer
 * @description A renderer that symbolizes features based on class breaks
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-renderers-ClassBreaksRenderer.html}
 */

/**
 * @class esri.renderers.UniqueValueRenderer
 * @description A renderer that symbolizes features based on unique values
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-renderers-UniqueValueRenderer.html}
 */

/**
 * @class esri.renderers.HeatmapRenderer
 * @description A renderer that visualizes the density of points as a raster surface
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-renderers-HeatmapRenderer.html}
 */

/**
 * @class esri.renderers.DotDensityRenderer
 * @description A renderer that visualizes data using a dot density technique
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-renderers-DotDensityRenderer.html}
 */

// =============================================================================
// WIDGETS
// =============================================================================

/**
 * @class esri.widgets.Widget
 * @description The base class for all widgets
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Widget.html}
 */

/**
 * @class esri.widgets.Popup
 * @description The popup widget displays content in a popup window
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Popup.html}
 */

/**
 * @class esri.widgets.Search
 * @description The Search widget enables users to search for locations
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Search.html}
 */

/**
 * @class esri.widgets.LayerList
 * @description The LayerList widget displays a list of layers
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-LayerList.html}
 */

/**
 * @class esri.widgets.Legend
 * @description The Legend widget displays legends for the layers in a map
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Legend.html}
 */

/**
 * @class esri.widgets.BasemapGallery
 * @description The BasemapGallery widget displays a gallery of basemaps
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-BasemapGallery.html}
 */

/**
 * @class esri.widgets.BasemapToggle
 * @description The BasemapToggle widget toggles between two basemaps
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-BasemapToggle.html}
 */

/**
 * @class esri.widgets.Editor
 * @description The Editor widget provides a framework for editing features
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Editor.html}
 */

/**
 * @class esri.widgets.Sketch
 * @description The Sketch widget provides functionality to create graphics
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Sketch.html}
 */

/**
 * @class esri.widgets.Measurement
 * @description The Measurement widget provides tools to measure area and distance
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Measurement.html}
 */

/**
 * @class esri.widgets.Attribution
 * @description The Attribution widget displays attribution text for the layers
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Attribution.html}
 */

/**
 * @class esri.widgets.Zoom
 * @description The Zoom widget provides buttons for zooming in and out
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Zoom.html}
 */

/**
 * @class esri.widgets.Home
 * @description The Home widget navigates the view to the initial extent
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Home.html}
 */

/**
 * @class esri.widgets.Locate
 * @description The Locate widget locates the user's current position
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Locate.html}
 */

/**
 * @class esri.widgets.Compass
 * @description The Compass widget displays a compass for navigation
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Compass.html}
 */

/**
 * @class esri.widgets.ScaleBar
 * @description The ScaleBar widget displays a scale bar
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-ScaleBar.html}
 */

/**
 * @class esri.widgets.TimeSlider
 * @description The TimeSlider widget provides temporal navigation
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-TimeSlider.html}
 */

/**
 * @class esri.widgets.Expand
 * @description The Expand widget can show or hide a widget within a panel
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Expand.html}
 */

// =============================================================================
// TASKS
// =============================================================================

/**
 * @class esri.tasks.Task
 * @description The base class for all task classes
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-Task.html}
 */

/**
 * @class esri.tasks.QueryTask
 * @description Executes queries against a layer in a service
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-QueryTask.html}
 */

/**
 * @class esri.tasks.IdentifyTask
 * @description Identifies features at a given location
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-IdentifyTask.html}
 */

/**
 * @class esri.tasks.FindTask
 * @description Searches for features that contain the given search text
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-FindTask.html}
 */

/**
 * @class esri.tasks.GeometryService
 * @description Performs geometric calculations and operations
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-GeometryService.html}
 */

/**
 * @class esri.tasks.Locator
 * @description Geocodes addresses and finds locations
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-Locator.html}
 */

/**
 * @class esri.tasks.RouteTask
 * @description Solves routing problems like finding the best route
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-RouteTask.html}
 */

/**
 * @class esri.tasks.ClosestFacilityTask
 * @description Finds the closest facilities to incidents
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-ClosestFacilityTask.html}
 */

/**
 * @class esri.tasks.ServiceAreaTask
 * @description Finds service areas around facilities
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-ServiceAreaTask.html}
 */

/**
 * @class esri.tasks.Geoprocessor
 * @description Executes geoprocessing tasks on the server
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-Geoprocessor.html}
 */

// =============================================================================
// ANALYSIS CLASSES
// =============================================================================

/**
 * @class esri.analysis.Analysis
 * @description The base class for all analysis classes
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-analysis-Analysis.html}
 */

/**
 * @class esri.analysis.LineOfSightAnalysis
 * @description Performs line of sight analysis in 3D
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-analysis-LineOfSightAnalysis.html}
 */

/**
 * @class esri.analysis.ViewshedAnalysis
 * @description Performs viewshed analysis in 3D
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-analysis-ViewshedAnalysis.html}
 */

/**
 * @class esri.analysis.SliceAnalysis
 * @description Performs slice analysis in 3D scenes
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-analysis-SliceAnalysis.html}
 */

/**
 * @class esri.analysis.DirectLineMeasurementAnalysis
 * @description Measures direct line distances in 3D
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-analysis-DirectLineMeasurementAnalysis.html}
 */

/**
 * @class esri.analysis.AreaMeasurementAnalysis
 * @description Measures areas in 3D scenes
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-analysis-AreaMeasurementAnalysis.html}
 */

/**
 * @class esri.analysis.DimensionAnalysis
 * @description Performs dimension analysis in 3D scenes
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-analysis-DimensionAnalysis.html}
 */

// =============================================================================
// PORTAL CLASSES
// =============================================================================

/**
 * @class esri.portal.Portal
 * @description The Portal class is used to work with ArcGIS Online and Portal for ArcGIS
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-portal-Portal.html}
 */

/**
 * @class esri.portal.PortalItem
 * @description The PortalItem class represents an item stored in a Portal
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-portal-PortalItem.html}
 */

/**
 * @class esri.portal.PortalUser
 * @description The PortalUser class represents a user in a Portal
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-portal-PortalUser.html}
 */

/**
 * @class esri.portal.PortalGroup
 * @description The PortalGroup class represents a group in a Portal
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-portal-PortalGroup.html}
 */

// =============================================================================
// IDENTITY AND SECURITY
// =============================================================================

/**
 * @class esri.identity.IdentityManager
 * @description Manages user authentication within an application
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-IdentityManager.html}
 */

/**
 * @class esri.identity.Credential
 * @description Contains information about an authenticated user
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html}
 */

/**
 * @class esri.identity.OAuthInfo
 * @description Contains information needed for OAuth authentication
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-OAuthInfo.html}
 */

/**
 * @class esri.identity.ServerInfo
 * @description Contains information about a server
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-ServerInfo.html}
 */

// =============================================================================
// SUPPORT CLASSES
// =============================================================================

/**
 * @class esri.PopupTemplate
 * @description The PopupTemplate class defines the content of popups
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-PopupTemplate.html}
 */

/**
 * @class esri.Camera
 * @description The Camera class defines the position and orientation of the camera
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-Camera.html}
 */

/**
 * @class esri.Basemap
 * @description The Basemap class contains a collection of layers
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-Basemap.html}
 */

/**
 * @class esri.Ground
 * @description The Ground class represents the ground surface of a Scene
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-Ground.html}
 */

/**
 * @class esri.TimeExtent
 * @description The TimeExtent class defines a temporal range
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-TimeExtent.html}
 */

/**
 * @class esri.TimeInterval
 * @description The TimeInterval class defines time intervals
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-TimeInterval.html}
 */

// =============================================================================
// REQUEST AND REST CLASSES
// =============================================================================

/**
 * @class esri.request
 * @description Makes requests to ArcGIS REST services and other web services
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-request.html}
 */

/**
 * @namespace esri.rest
 * @description Contains REST API helper functions and classes
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-rest.html}
 */

// =============================================================================
// FORM AND FIELD CLASSES
// =============================================================================

/**
 * @class esri.form.FormTemplate
 * @description Defines the structure and appearance of forms
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-form-FormTemplate.html}
 */

/**
 * @class esri.layers.support.Field
 * @description Information about each field in a FeatureLayer
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-support-Field.html}
 */

/**
 * @class esri.layers.support.FeatureSet
 * @description A collection of features returned from a task or query
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-support-FeatureSet.html}
 */

/**
 * @class esri.layers.support.LabelClass
 * @description Defines labels for a FeatureLayer
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-support-LabelClass.html}
 */

// =============================================================================
// PROJECTION AND COORDINATE SYSTEMS
// =============================================================================

/**
 * @class esri.geometry.projection
 * @description Projects geometries from one spatial reference to another
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-projection.html}
 */

/**
 * @class esri.geometry.coordinateFormatter
 * @description Formats coordinates in various formats
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-coordinateFormatter.html}
 */

// =============================================================================
// SMARTMAPPING
// =============================================================================

/**
 * @namespace esri.smartMapping
 * @description Contains modules for data-driven visualization
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-smartMapping.html}
 */

/**
 * @class esri.smartMapping.statistics.histogram
 * @description Generates histograms from data
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-smartMapping-statistics-histogram.html}
 */

// =============================================================================
// WEBGL AND 3D CLASSES
// =============================================================================

/**
 * @class esri.views.3d.externalRenderers
 * @description Allows custom WebGL rendering in 3D views
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-views-3d-externalRenderers.html}
 */

/**
 * @class esri.views.3d.environment.Environment
 * @description Defines the lighting and atmosphere of a SceneView
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri-views-3d-environment-Environment.html}
 */

// =============================================================================
// VERSION INFORMATION
// =============================================================================

/**
 * @constant {string} VERSION
 * @description The current version of the ArcGIS Maps SDK for JavaScript
 * @default "4.33"
 * @see {@link https://developers.arcgis.com/javascript/latest/api-reference/esri.html#VERSION}
 */