// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();
  static const String assets_css_overrides_override_outline_css =
      'assets/css_overrides/override_outline.css';
}