name: arcgis_map_sdk_web
description: Esri ArcGIS Flutter web implementation.
version: 0.8.0
repository: https://github.com/fluttercommunity/arcgis_map_sdk
maintainer: Matthaios Saitakis (@MatthaiosSait), Pascal Welsch (@passsy), Max Peters (@maxpeters)

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  arcgis_map_sdk_platform_interface: ^1.0.1
  async: ^2.9.0

  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2
  web: ^1.1.1

dev_dependencies:
  lint: ^2.8.0

flutter:
  plugin:
    implements: arcgis_map_sdk
    platforms:
      web:
        pluginClass: ArcgisMapWeb
        fileName: arcgis_map_web_js.dart

  assets:

    - assets/css_overrides/
